In [6]:
# https://pt.stackoverflow.com/questions/595202/consumindo-api-do-jira-montar-an%c3%a1lise-de-quantidade-de-itens-entregues-por-sema

In [7]:
import pandas as pd

In [8]:
datas = [
    "2024-05-31T11:49:48.749-0300",
    "2024-06-03T15:18:09.427-0300",
    "2024-05-14T09:24:13.761-0300",
    "2024-06-03T10:46:07.084-0300",
    "2024-05-20T17:32:26.328-0300",
    "2024-05-17T09:47:10.918-0300",
    "2024-05-13T15:40:20.749-0300",
    "2024-05-17T09:47:19.072-0300",
    "2024-05-21T10:39:55.807-0300",
    "2024-05-20T18:10:04.094-0300",
    "2024-06-03T10:46:13.372-0300",
    "2024-05-17T09:47:15.363-0300",
    "2024-05-10T09:45:10.498-0300",
    "2024-05-16T14:39:59.261-0300",
    "2024-05-20T16:32:09.483-0300",
    "2024-05-20T10:48:34.883-0300",
    "2024-05-20T16:31:24.936-0300",
    "2024-05-20T16:30:44.126-0300",
    "2024-05-20T16:50:15.562-0300",
    "2024-05-20T16:44:56.853-0300",
    "2024-05-20T16:21:01.481-0300",
    "2024-05-20T16:46:17.485-0300",
    "2024-05-21T09:28:23.737-0300",
    "2024-05-20T16:48:29.219-0300",
    "2024-05-20T16:17:59.871-0300",
    "2024-05-20T16:49:41.132-0300",
    "2024-05-20T17:12:37.075-0300",
    "2024-05-20T16:54:19.876-0300",
    "2024-05-20T17:09:00.893-0300",
    "2024-05-20T16:54:09.553-0300",
    "2024-05-20T18:11:07.269-0300",
    "2024-05-20T17:12:54.058-0300",
    "2024-05-20T17:13:24.961-0300",
    "2024-05-20T17:13:33.589-0300",
    "2024-05-20T17:09:58.555-0300",
    "2024-05-20T17:09:45.912-0300",
    "2024-05-20T17:27:11.884-0300",
    "2024-05-20T17:10:33.869-0300",
    "2024-05-20T17:10:18.530-0300",
    "2024-05-20T17:12:01.089-0300",
    "2024-05-20T16:49:16.779-0300",
    "2024-05-20T16:49:30.100-0300",
    "2024-05-20T16:51:09.395-0300",
    "2024-05-20T16:52:09.616-0300",
    "2024-05-20T16:52:50.412-0300",
    "2024-05-20T16:52:38.361-0300",
    "2024-05-20T18:09:12.804-0300",
]

In [9]:
df = pd.DataFrame(datas, columns=["data"])

df["data"] = pd.to_datetime(df["data"])

df["inicio_mes"] = df["data"].values.astype("datetime64[M]")

df["mes"] = df["data"].dt.month
df["ano"] = df["data"].dt.year
df["week_data"] = df["data"].dt.isocalendar().week
df["week_inicio_mes"] = df["inicio_mes"].dt.isocalendar().week

df["semana_do_mes"] = df["week_data"] - df["week_inicio_mes"] + 1

df_resultado = (
    df[["data", "semana_do_mes", "mes", "ano"]]
    .groupby(["ano", "mes", "semana_do_mes"], as_index=False)
    .size()
    .rename({"size": "issues"}, axis=1)
)

df_resultado

    ano  mes  semana_do_mes  issues
0  2024    5              2       1
1  2024    5              3       6
2  2024    5              4      36
3  2024    5              5       1
4  2024    6              2       3

In [10]:
# Como não existe um impeditivo de utilizar alguma lib externa no enunciado, uma possível solução utilizando pandas:

#     import pandas as pd

#     datas = [
#         '2024-05-31T11:49:48.749-0300', '2024-06-03T15:18:09.427-0300',
#         '2024-05-14T09:24:13.761-0300', '2024-06-03T10:46:07.084-0300',
#         '2024-05-20T17:32:26.328-0300', '2024-05-17T09:47:10.918-0300',
#         '2024-05-13T15:40:20.749-0300', '2024-05-17T09:47:19.072-0300',
#         '2024-05-21T10:39:55.807-0300', '2024-05-20T18:10:04.094-0300',
#         '2024-06-03T10:46:13.372-0300', '2024-05-17T09:47:15.363-0300',
#         '2024-05-10T09:45:10.498-0300', '2024-05-16T14:39:59.261-0300',
#         '2024-05-20T16:32:09.483-0300', '2024-05-20T10:48:34.883-0300',
#         '2024-05-20T16:31:24.936-0300', '2024-05-20T16:30:44.126-0300',
#         '2024-05-20T16:50:15.562-0300', '2024-05-20T16:44:56.853-0300',
#         '2024-05-20T16:21:01.481-0300', '2024-05-20T16:46:17.485-0300',
#         '2024-05-21T09:28:23.737-0300', '2024-05-20T16:48:29.219-0300',
#         '2024-05-20T16:17:59.871-0300', '2024-05-20T16:49:41.132-0300',
#         '2024-05-20T17:12:37.075-0300', '2024-05-20T16:54:19.876-0300',
#         '2024-05-20T17:09:00.893-0300', '2024-05-20T16:54:09.553-0300',
#         '2024-05-20T18:11:07.269-0300', '2024-05-20T17:12:54.058-0300',
#         '2024-05-20T17:13:24.961-0300', '2024-05-20T17:13:33.589-0300',
#         '2024-05-20T17:09:58.555-0300', '2024-05-20T17:09:45.912-0300',
#         '2024-05-20T17:27:11.884-0300', '2024-05-20T17:10:33.869-0300',
#         '2024-05-20T17:10:18.530-0300', '2024-05-20T17:12:01.089-0300',
#         '2024-05-20T16:49:16.779-0300', '2024-05-20T16:49:30.100-0300',
#         '2024-05-20T16:51:09.395-0300', '2024-05-20T16:52:09.616-0300',
#         '2024-05-20T16:52:50.412-0300', '2024-05-20T16:52:38.361-0300',
#         '2024-05-20T18:09:12.804-0300'
#     ]

# Criando o dataframe

#     df = pd.DataFrame(datas, columns=['data'])

# Convertendo string em data no pandas

#     df['data'] = pd.to_datetime(df['data'])

# Data do inicio do mês, será para calcular diferenças entre as datas

#     df['inicio_mes'] = df['data'].values.astype('datetime64[M]')

# Campos que serão utilizados na agregação

#     df['mes'] = df['data'].dt.month
#     df['ano'] = df['data'].dt.year

# Pegando o dia dentro da semana

#     df['week_data'] = df['data'].dt.isocalendar().week

# Pegando a semana em que o primeiro dia do mês aparece

#     df['week_inicio_mes'] = df['inicio_mes'].dt.isocalendar().week

# Calculo da diferença para saber qual é a semana dentro do mês (semana do ano - semana do mês)

#     df['semana_do_mes'] = df['week_data'] - df['week_inicio_mes'] + 1

# Agregação para saber qual a quantidade de issues dentro do ano/mês/semana

#     df_resultado = (df[['data', 'semana_do_mes', 'mes', 'ano']]
#      .groupby([ 'ano', 'mes','semana_do_mes'], as_index=False)
#      .size()
#      .rename({'size':'issues'},axis=1))

#     df_resultado

# |   |  ano | mes | semana_do_mes | issues |
# |--:|-----:|----:|--------------:|-------:|
# | 0 | 2024 |   5 |             2 |      1 |
# | 1 | 2024 |   5 |             3 |      6 |
# | 2 | 2024 |   5 |             4 |     36 |
# | 3 | 2024 |   5 |             5 |      1 |
# | 4 | 2024 |   6 |             2 |      3 |